"""empty message

Revision ID: 15671de69e44
Revises: 
Create Date: 2019-08-15 14:18:46.219809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15671de69e44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bird_mappings',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('vec_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('file', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pi_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_set_timestamp'), 'data_set', ['timestamp'], unique=False)
    op.create_table('fusion_hypotheses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=False),
    sa.Column('covariance', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fusion_hypotheses_timestamp'), 'fusion_hypotheses', ['timestamp'], unique=False)
    op.create_table('classification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('bird_id', sa.Integer(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['data_set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('angle', sa.Float(), nullable=True),
    sa.Column('deviation', sa.Float(), nullable=True),
    sa.Column('sig_pow', sa.Float(), nullable=True),
    sa.Column('snr', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['data_set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurement')
    op.drop_table('classification')
    op.drop_index(op.f('ix_fusion_hypotheses_timestamp'), table_name='fusion_hypotheses')
    op.drop_table('fusion_hypotheses')
    op.drop_index(op.f('ix_data_set_timestamp'), table_name='data_set')
    op.drop_table('data_set')
    op.drop_table('bird_mappings')
    # ### end Alembic commands ###
